AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus HTTP - quarkus-lambda-rest-dynamodb-1.0.0-SNAPSHOT
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"
      
Parameters:
  RoleName:
    Type: String
    Default: APIRole
  Runtime:
    Type: String
    Default: provided
    AllowedValues:
    - java11
    - provided
    Description: use java11 for jvm runtime or provided for native runtime
  MemorySize:
    Type: String
    Default: 128
    Description: Memory size in MB
  DisableSignalHandlers:
    Type: String
    Default: true
    Description: Set to true when using native builds
  SnapStartApplyOn:
    Type: String
    Default: None
    AllowedValues:
    - None
    - PublishedVersions    
    Description: Set to SnapStart when to enable it

Resources:

  QuarkusLambdaRestDynamodb:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: !Sub ${Runtime}
      CodeUri: ../target/function.zip
      MemorySize: !Sub ${MemorySize}
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${RoleName}'
      Timeout: 15
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: !Sub ${DisableSignalHandlers}
      SnapStart:
        ApplyOn: !Sub ${SnapStartApplyOn}
      AutoPublishAlias: V1          
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  QuarkusLambdaRestDynamodbApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fruits'
           