version = 0.1

[default.deploy.parameters]
stack_name = "sam-app-native"
resolve_s3 = true
s3_prefix = "sam-app-native"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[prereqs.deploy.parameters]
stack_name = "sam-app-prereqs"
resolve_s3 = true
s3_prefix = "sam-app-prereqs"
capabilities = "CAPABILITY_NAMED_IAM"

[jvm.deploy.parameters]
stack_name = "sam-app-jvm"
resolve_s3 = true
s3_prefix = "sam-app-jvm"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Runtime=\"java11\" MemorySize=\"512\" DisableSignalHandlers=\"false\""

[snapstart.deploy.parameters]
stack_name = "sam-app-snapstart"
resolve_s3 = true
s3_prefix = "sam-app-snapstart"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Runtime=\"java11\" MemorySize=\"512\" DisableSignalHandlers=\"false\" PublishAlias=\"SnapStart\""