version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[jvm.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Runtime=\"java11\" MemorySize=\"512\" DisableSignalHandlers=\"false\""
